service:
  name: serverless-equipment-status-app
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-reqvalidator-plugin # For validating requests
  - serverless-aws-documentation # For validating requests
  - serverless-iam-roles-per-function

provider:
  # Enabling XRay tracing
  tracing:
    lambda: true
    apiGateway: true

  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-1'}

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    EQUIPMENT_TABLE: Equipment-${self:provider.stage}
    EQUIPMENT_CREATEDAT_INDEX: CreatedAtIndex
    ATTACHMENT_S3_BUCKET: quyen-serverless-equipment-status-images-${self:provider.stage} # Bucket to store attached image
    SIGNED_URL_EXPIRATION: 300

  iamRoleStatements:

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  
  # SNS topic name
  topicName: equipmentImagesTopic-${self:provider.stage}

  # For validating requests
  documentation:
    api:
      info:
        version: v1.0.0
        title: Equipment Status API
        description: Serverless application for equipment status
    models:
      - name: CreateEquipmentRequest
        contentType: application/json
        schema: ${file(models/create-eq-model.json)}
      - name: UpdateEquipmentRequest
        contentType: application/json
        schema: ${file(models/update-eq-model.json)}


functions:
  # Handle authorization
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  # Get list of equipment
  GetEquipmentList:
    handler: src/lambda/http/getEquipmentList.handler
    events:
      - http:
          method: get
          path: equipment
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.EQUIPMENT_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.EQUIPMENT_TABLE}/index/${self:provider.environment.EQUIPMENT_CREATEDAT_INDEX}

  # Create a new equipment
  CreateEquipment:
    handler: src/lambda/http/createEquipment.handler
    events:
      - http:
          method: post
          path: equipment
          cors: true
          authorizer: Auth
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new equipment
            description: Create a new equipment
            requestModels:
              'application/json': CreateEquipmentRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.EQUIPMENT_TABLE}

  # Update an equipment
  UpdateEquipment:
    handler: src/lambda/http/updateEquipment.handler
    events:
      - http:
          method: patch
          path: equipment/{equipmentId}
          cors: true
          authorizer: Auth
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Update an equipment
            description: Update an equipment
            requestModels:
              'application/json': UpdateEquipmentRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.EQUIPMENT_TABLE}
  
  # Delete an equipment
  DeleteEquipment:
    handler: src/lambda/http/deleteEquipment.handler
    events:
      - http:
          method: delete
          path: equipment/{equipmentId}
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.EQUIPMENT_TABLE}

  # Create a presigned URL used for uploading an image to S3 bucket
  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: equipment/{equipmentId}/attachment
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.EQUIPMENT_TABLE}
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: arn:aws:s3:::${self:provider.environment.ATTACHMENT_S3_BUCKET}/*

  # Save information about the upload when SNS notifies a file is uploaded to S3
  RecordUploadHistory:
    handler: src/lambda/s3/recordUploadHistory.handler
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - arn:aws:sns
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - ${self:custom.topicName}
          topicName: ${self:custom.topicName}


resources:
  Resources:
    # Allow API Gateway to set correct CORS headers if our custom authorizor fails
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    
    # For validating the create and update equipment requests
    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false

    # Create a DynamoDB table with local secondary index and a composite key
    EquipmentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: equipmentId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH # Partition key
          - AttributeName: equipmentId
            KeyType: RANGE # Sort key
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.EQUIPMENT_TABLE}
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.EQUIPMENT_CREATEDAT_INDEX}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL # What attributes will be copied to an index

    # Create a S3 Bucket
    # S3 bucket is configured to call SNS upon file upload
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      DependsOn: SNSTopicPolicy
      Properties:
        BucketName: ${self:provider.environment.ATTACHMENT_S3_BUCKET}
        NotificationConfiguration:
          TopicConfigurations:
            - Event: s3:ObjectCreated:Put
              Topic: !Ref ImagesTopic
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

    # Define S3 Bucket policy and attach it to the bucket defined above
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.ATTACHMENT_S3_BUCKET}/*'
        Bucket: !Ref AttachmentsBucket

    # SNS Topic
    ImagesTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Image bucket topic
        TopicName: ${self:custom.topicName}

    # SNS Topic Policy. This allows S3 to send events to this SNS topic.
    SNSTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                AWS: "*"
              Action: sns:Publish
              Resource:
                !Ref ImagesTopic
              Condition:
                ArnLike:
                  AWS:SourceArn: arn:aws:s3:::${self:provider.environment.ATTACHMENT_S3_BUCKET}
        Topics:
          - !Ref ImagesTopic